--creating of book sales reccords table structure
--Authors: group_by
CREATE TABLE group_by (
    id INT PRIMARY KEY,
    purchase_date_time VARCHAR(50),
    purchase_date VARCHAR(50),
    purchase_time VARCHAR(50),
    quarter VARCHAR(50),
    qtr INT,
    purchase_year INT,
    purchase_month INT,
    purchase_day INT,
    special_day INT,
    online_sale_offers INT,
    day_of_week INT,
    weekend INT,
    morning INT,
    afternoon INT,
    evening INT,
    night INT,
    gender_binary INT,
    customer_id VARCHAR(50),
    gender VARCHAR(50),
    product_name VARCHAR(255),
    item_status VARCHAR(50),
    quantity INT,
    currency VARCHAR(50),
    item_price NUMERIC,
    shipping_price NUMERIC,
    ship_city VARCHAR(50),
    ship_state VARCHAR(50),
    ship_postal_code VARCHAR(50),
    category VARCHAR(50),
    total_amount NUMERIC,
    author VARCHAR(128),
    publisher VARCHAR(128),
    profit_percentage NUMERIC,
    profit_inr NUMERIC,
    cost_of NUMERIC
);
